application:
  port: 8000
  base_url: "http://127.0.0.1"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  authorization_token: "my-secret-token"
  base_url: "localhost"
  sender_email: "test@gmail.com"
  timeout_milliseconds: 10000
